<?php

include_once('lc_decisions.features.inc');

/**
* Implementation of hook_init().
*/
function lc_decisions_init() {
  drupal_add_css(drupal_get_path('module', 'lc_decisions') .'/lc_decisions.css');
}

/**
* Implementation of hook_help().

function lc_decisions_help($path) {
  // Central help page content.
  if ($path == 'admin/help#lc_decisions') {
    $help = '<h3>'. t('LC Decisions') .'</h3>';
    $help .= '<p>'. t("The polling area lets you poll your team and then see the results.") .'</p>';
    $help .= '<p>'. t("To add a poll, navigate to the lc_decisions area and click the __Add poll__ button.  Then click __Save__.") .'</p>';
    return $help;
  }

  // Contextual help content.
  if (context_isset('context', 'spaces-feature-poll')) {
    if ($path == 'node/add/decision') {
      $help = '';
      $help .= '<h3>'. t('Poll') .'</h3>';
      $help .= '<p>'. t("Post a poll in this group. The polling question and results will be shared will all team members in the Polling area.") .'</p>';
      return $help;
    }
    else {
      $help = '<h3>'. t('lc_decisions') .'</h3>';
      $help .= '<p>'. t("The lc_decisions feature lets you post lc_decisions in a group and then see the results.") .'</p>';
      return $help;
    }
  }
}
*/
